name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build and Test
        run: mvn --batch-mode --update-snapshots clean package -P validator

      - name: Set settings.xml
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "mks-repo",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            },
            {
              "id": "mks-repo-snapshots",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'mekomsolutions' }}

      - name: Publish
        run: mvn --batch-mode clean deploy -P validator
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'mekomsolutions' }}
